// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbiwjjdvnoicsizipgek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiaXdqamR2bm9pY3NpemlwZ2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTk4OTIsImV4cCI6MjA3MTQ3NTg5Mn0.AevIXNLyQW_lH7PijS362p2jPyC2gGB4RguwhuFdIf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});